version: '3'

services:
  backend:
    image: letuan45/shop-management-product-backend
    container_name: shop_management_product_api
    environment:
      - DATABASE_URL=postgresql://postgres:lelamtuan@shop-management-instance.c7cs0m28m6l4.ap-southeast-2.rds.amazonaws.com:5432/shop_management_product?schema=public
      - AMQP_PRODUCT_URL=amqps://iiyscote:OqxkEgQlzP46BNcT1uhrUAVCdg9gtFHT@armadillo.rmq.cloudamqp.com/iiyscote
    restart: 'always'
